title: misslt
description: misslt.com docs site
logo: /assets/images/logo.png
github: https://www.github.com/moebiusever
plugins:
  - jekyll-relative-links
  - jekyll-paginate
  - jekyll-gist
paginate: 20
per_page: 20
paginate_path: "/page:num/"